name: E2E-Tests
on:
  pull_request:
    types: [opened, reopened]
  workflow_run:
    workflows: [Main] # must exactly match previous workflow name
    types: [completed]
    # branches-ignore: [master, main]

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success') && (github.event_name == 'pull_request') }}
    steps:
      - name: Run E2E tests
        run: echo Done
