name: E2E-Tests
on:
  pull_request:
    branches:
      - run-on-pr-only
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' }}
    steps:
      - name: Run E2E tests
        run: echo Done test
