name: Tests
on:
  pull_request:
    types: [opened]
  workflow_run:
    workflows: [Main] # must exactly match previous workflow name
    types:
      - completed

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'pull_request' }}
    steps:
      - name: Run tests
        run: echo Done
